### ISSUE TITLE
Sometimes it doesn't load

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/rsvp#19]
@ycp217 - Not really sure why or what happens. Software....

https://www.facebook.com/events/423452541198600/permalink/425795480964306/, https://www.facebook.com/events/423452541198600/permalink/424156414461546/

From what I can figure it _firstly_ be one of the packages we import. OR it can be a devops problem. I'll enable a bunch of logs and let's try figure it out.

```
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inconsolata:400, 700">
<script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="//cdn.rawgit.com/jpillora/xdomain/0.7.3/dist/xdomain.min.js" slave="https://api.tnyu.org/v2/proxy.html"></script>
<script src="https://fb.me/react-with-addons-0.13.3.js"></script>
<script src="https://fb.me/JSXTransformer-0.13.3.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
```

**Comment by juliepanda** [comment]
O.O
Can't reproduce. But, I'll check it out.
Maybe it's this: https://github.com/facebook/react/issues/2829

**Comment by AbhiAgarwal** [comment]
We should probably move to using local copies of these libraries and see if that fixes the issue. I'm not too certain what else could be the issue.. The website just doesn't load means that there are some edge cases we're not considering. Either it's the API or the libraries or some case that's not handled in the code.

**Comment by juliepanda** [comment]
Done!

**Comment by juliepanda** [comment]
Realized that the site doesn't load in Safari because it doesn't support some es2015 syntax yet.

**Comment by AbhiAgarwal** [comment]
@ycp217 oh glad you caught that!
