### ISSUE TITLE
Collect skills/wantsToLearn data etc

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/rsvp#20]
When someone rsvps to an event, it's a good opportunity (I think) to get them to fill out more data about themselves. We need to be clear though, that:
1. Providing all this data is totally optional and a one-time thing, so the resulting form doesn't look too annoying to fill out and doesn't discourage people from completing the rsvp. in fact, the form should probably only appear after the rsvp's gone through and we've gotten essential data like email and n-number.
2. For each data item we're asking for, we should clearly explain why we need it. E.g. skills, wantsToLearn, wantsToHire are so we can match you with events, jobs, and project collaborators. Etc.

**Comment by juliepanda** [comment]
We can certainly do that here, but if only admin can create a new skill, we'd have to pre-populate it with a bunch of buzzwords before we add this.

**Comment by ethanresnick** [comment]
Skills should already be prepopulated! Try getting `/skills`. If you see any that are missing, lmk and we'll add them.
