### ISSUE TITLE
Leaving n-number/skills/etc permanently

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/rsvp#26]
Can we leave it there permanently? If people miss-enter their N-Number the first time it becomes really hard to re-enter it (or impossible). Let us just leave it there!

**Comment by juliepanda** [comment]
k

**Comment by juliepanda** [comment]
Sorta doing it here now at here:
d2774cbd1480ea10e026d3f46a5e156589bb18af (sets up actions)
fcd65094be925338c95205084052203dd73f782e (load person info again)
If people input the wrong thing, then they just do it again from Profile.
