### ISSUE TITLE
Have a login to Facebook button instead of auto-redirect

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/rsvp#3]

**Comment by juliepanda** [comment]
Just a name, email form for people who don't login with Facebook?

**Comment by AbhiAgarwal** [comment]
@ycp217 hi! no currently it just redirects to the Facebook login automatically. Maybe if the person isn't logged in then have a button that says Login with Facebook? 

It's just because it's hard to tell what's happening if you automatically redirect to Facebook. At least for a user who isn't on our board and understands what it is doing.

**Comment by juliepanda** [comment]
OK
