### ISSUE TITLE
Stuck in loading after adding email

### ISSUE THREAD

**Issue by NYDrewReynolds** [TechAtNYU/rsvp#35]
I went to my Profile and added my email address. When I clicked Submit, I was only show "...Tech@NYU RSVP is loading."

**Profile Page**

<img width="1275" alt="screen shot 2016-03-31 at 3 30 44 pm" src="https://cloud.githubusercontent.com/assets/2224702/14188324/a1c3a872-f755-11e5-9d48-0a8b1f1f8e0e.png">

**Event List**
<img width="1267" alt="screen shot 2016-03-31 at 3 32 06 pm" src="https://cloud.githubusercontent.com/assets/2224702/14188350/c0fa9f70-f755-11e5-8c21-a4b472bd41bf.png">

**Comment by juliepanda** [comment]
added validator! thanks!
