### ISSUE TITLE
make it pretty

### ISSUE THREAD

**Issue by juliepanda** [TechAtNYU/rsvp#5]

**Comment by oa495** [comment]
![screen shot 2015-10-10 at 8 29 35 pm](https://cloud.githubusercontent.com/assets/8635106/10413991/bb7a1940-6f8d-11e5-9d06-bd932309ac0d.png)
![screen shot 2015-10-10 at 8 29 26 pm](https://cloud.githubusercontent.com/assets/8635106/10413990/bb79f5fa-6f8d-11e5-81b9-3720ae3b655b.png)

running on localhost vs actual site. why are they so different?

**Comment by juliepanda** [comment]
idk, but I still see the old style when I go to https://rsvp.techatnyu.org
![screen shot 2015-10-10 at 8 52 21 pm](https://cloud.githubusercontent.com/assets/7796312/10414108/eeb88794-6f90-11e5-8398-2213cc80594d.png)

**Comment by juliepanda** [comment]
Maybe give it a while?

**Comment by AbhiAgarwal** [comment]
checkit now. the update time on the CDN was set _too_ high. Now it's set for 15 minutes :D

**Comment by oa495** [comment]
so I don't think the issue is that it's not updating because some of my styles are there: it's floated to the left, the layout of the date & time and the header is there. it's just not retrieving all the styles?

**Comment by juliepanda** [comment]
i think maybe `<img src="images/techatnyu.png">` is actually not being loaded and therefore is not taking up any space for the header to show?

**Comment by oa495** [comment]
the logo is being loaded on the screenshot I shared (the first one) which is what I saw on http://rsvp.techatnyu.org/

**Comment by juliepanda** [comment]
![screen shot 2015-10-10 at 10 13 04 pm](https://cloud.githubusercontent.com/assets/7796312/10414312/1f54fe68-6f9c-11e5-8b8d-5526f4cd6a49.png)
This is what I see rn

**Comment by oa495** [comment]
![screen shot 2015-10-10 at 10 14 22 pm](https://cloud.githubusercontent.com/assets/8635106/10414323/79c6861e-6f9c-11e5-8f00-952512468c17.png)
i see this

**Comment by phiott** [comment]
@oa495 Can you try and do it on incognito? (this is Abhi on Phil's laptop)

![hi](http://files.tnyu.org/upload_6b447e17af38ab4cbd5a0140f92d5798_gg.png)

**Comment by juliepanda** [comment]
That's what I did earlier, but it works now. idk what happened lol.
![screen shot 2015-10-10 at 10 21 22 pm](https://cloud.githubusercontent.com/assets/7796312/10414335/45e5b53a-6f9d-11e5-8e8c-79e5b9c9edf8.png)

**Comment by phiott** [comment]
hahaha. Rackspace is a little slow at updating things for some reason. I'm not too sure why it's slow tbh

**Comment by oa495** [comment]
works in incognito! guess I'll just wait it out.

**Comment by AbhiAgarwal** [comment]
:100: also do like a hard refresh - command shift R
