### ISSUE TITLE
make event(s) unavailable if full

### ISSUE THREAD

**Issue by juliepanda** [TechAtNYU/rsvp#6]

**Comment by AbhiAgarwal** [comment]
Actually had an idea for this! We have venues, and the event uses a venue on the API. Venues have number of seats. Maybe we can do some kind of math like number of seats \* 3 to be an upper bound on attendance limit? Then when the limit is reached can just show the event as "Full" and no one can RSVP to it.

**Comment by juliepanda** [comment]
Sounds reasonable. We can do this. And do a default of 100 \* 3 if capacity not available. :ok_hand:
